"""
Mappings pour la taxonomie complète LVMH
Modules d'extraction de tags par catégorie
"""

from .identity import GENRE_MAPPING, LANGUE_MAPPING, STATUT_MAPPING, PROFESSIONS_ADVANCED
from .location import CITIES_ADVANCED
from .lifestyle import SPORT_MAPPING, MUSIQUE_MAPPING, ANIMAUX_MAPPING, VOYAGE_MAPPING, ART_CULTURE_MAPPING, GASTRONOMIE_MAPPING
from .style import PIECES_MAPPING, COULEURS_ADVANCED, MATIERES_ADVANCED, SENSIBILITE_MODE, TAILLES_MAPPING
from .purchase import MOTIF_ADVANCED, TIMING_MAPPING, MARQUES_LVMH, FREQUENCE_ACHAT
from .preferences import REGIME_MAPPING, ALLERGIES_MAPPING, VALEURS_MAPPING
from .tracking import ACTIONS_MAPPING, ECHEANCES_MAPPING, CANAUX_MAPPING

__all__ = [
    # Identity
    'GENRE_MAPPING', 'LANGUE_MAPPING', 'STATUT_MAPPING', 'PROFESSIONS_ADVANCED',
    # Location
    'CITIES_ADVANCED',
    # Lifestyle
    'SPORT_MAPPING', 'MUSIQUE_MAPPING', 'ANIMAUX_MAPPING', 'VOYAGE_MAPPING', 
    'ART_CULTURE_MAPPING', 'GASTRONOMIE_MAPPING',
    # Style
    'PIECES_MAPPING', 'COULEURS_ADVANCED', 'MATIERES_ADVANCED', 'SENSIBILITE_MODE', 'TAILLES_MAPPING',
    # Purchase
    'MOTIF_ADVANCED', 'TIMING_MAPPING', 'MARQUES_LVMH', 'FREQUENCE_ACHAT',
    # Preferences
    'REGIME_MAPPING', 'ALLERGIES_MAPPING', 'VALEURS_MAPPING',
    # Tracking
    'ACTIONS_MAPPING', 'ECHEANCES_MAPPING', 'CANAUX_MAPPING'
]
